version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"

  - package-ecosystem: npm
    directory: "/apps/publisher-app"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "app"

  - package-ecosystem: npm
    directory: "/plugins/publisher-main"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "npm"
      - "plugin"

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "github actions"
      - "ci"